### Add a blog
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Hybanth's First Blog",
  "author": "Hybanth",
  "url": "https://hybanth.github.io/blog",
  "likes": 77
}

### Add another blog
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "SpriteSpawn's First Blog",
  "author": "Hybee",
  "url": "https://SpriteSpawn.github.io/blog",
  "likes": 10
}

### Get all blogs
GET http://localhost:3003/api/blogs
